
export class CommonConst {
  static DATABASE_DOMAIN_CONNECTION = 'DATABASE_DOMAIN_CONNECTION';
  static DATABASE_QUERY_CONNECTION = 'DATABASE_QUERY_CONNECTION';

  static DOMAIN_MODEL_TOKEN = 'Domain-ModelToken';
  static QUERY_MODEL_TOKEN = 'Query-ModelToken';
}